### ISSUE TITLE
please provide setup.py

### ISSUE THREAD

**Issue by yarikoptic** [juhakivekas/multidiff#1]
and possibly make multidiff into a `multidiff` Python package while at it ;)  It would simplify its distribution (e.g. via pypi), packaging, and (re)use (as a Python module).

**Comment by juhakivekas** [comment]
setup.py, definitely.

I haven’t packaged this because I’ve never packaged anything python. I’m also a bit unsure what to include since I’d like to keep the utility separate from the internals (stuff in `multidiff/`). Also it might be good to wait with the pypi since stuff inside is going to change a lot.

**Comment by yarikoptic** [comment]
examples are numerous!  Not the prettiest but might be one of the simple ones is e.g. https://github.com/duecredit/duecredit/blob/master/setup.py#L88  -- `entry_points` define what cmdline utility would be created to point to some functionality inside.
as far as utility uses internals, they should come together anyways.  Low release version would suggest that API is still in flux, so to not expect the module to retain its API "forever".
